import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Shield } from "lucide-react";

export default function GoogleFirebaseSecurity() {
  const [open, setOpen] = useState(false);

  return (
    <>
      <Button variant="outline" onClick={() => setOpen(true)} className="flex items-center gap-2">
        <Shield className="h-4 w-4" />
        Security
      </Button>
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Firebase Security & Permissions</DialogTitle>
          </DialogHeader>
          <div className="space-y-5 text-sm text-muted-foreground">

            <div className="bg-destructive/10 p-3 rounded text-xs">
              <p className="font-medium text-foreground">⚠️ Never leave test mode open in production</p>
              <p>The default "test mode" rules allow anyone to read and write your database. Lock it down before going live.</p>
            </div>

            <div>
              <h3 className="font-semibold text-foreground mb-2">1. Firestore Security Rules</h3>
              <p className="mb-2">Go to <strong>Firestore Database → Rules</strong> tab in the Firebase Console.</p>

              <p className="mb-1 text-xs font-medium text-foreground">Locked down (no public access):</p>
              <pre className="bg-muted rounded p-2 text-xs overflow-x-auto whitespace-pre-wrap break-words mb-3">
{`rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if false;
    }
  }
}`}
              </pre>

              <p className="mb-1 text-xs font-medium text-foreground">Authenticated users only:</p>
              <pre className="bg-muted rounded p-2 text-xs overflow-x-auto whitespace-pre-wrap break-words mb-3">
{`rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth != null;
    }
  }
}`}
              </pre>

              <p className="mb-1 text-xs font-medium text-foreground">Per-user data (users can only access their own docs):</p>
              <pre className="bg-muted rounded p-2 text-xs overflow-x-auto whitespace-pre-wrap break-words">
{`rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /records/{docId} {
      allow read, write: if request.auth != null
        && request.auth.uid == resource.data.uid;
    }
  }
}`}
              </pre>
            </div>

            <hr className="border-border" />

            <div>
              <h3 className="font-semibold text-foreground mb-2">2. Restrict Access by Domain (Google Identity Platform)</h3>
              <ol className="list-decimal list-inside space-y-1 ml-2 text-xs">
                <li>Go to <strong>Authentication → Sign-in method</strong> in Firebase Console</li>
                <li>Enable <strong>Google</strong> or <strong>Email/Password</strong> sign-in</li>
                <li>Under <strong>Authorized domains</strong>, add only your app's domain</li>
                <li>Remove <code className="bg-muted px-1 rounded">localhost</code> from authorized domains before going live</li>
              </ol>
            </div>

            <hr className="border-border" />

            <div>
              <h3 className="font-semibold text-foreground mb-2">3. API Key Restrictions (Google Cloud Console)</h3>
              <ol className="list-decimal list-inside space-y-1 ml-2 text-xs">
                <li>Go to <a href="https://console.cloud.google.com/apis/credentials" target="_blank" rel="noopener noreferrer" className="text-primary underline">console.cloud.google.com/apis/credentials</a></li>
                <li>Find the API key generated by Firebase (named <em>Browser key (auto created by Firebase)</em>)</li>
                <li>Click it → under <strong>Application restrictions</strong>, select <strong>HTTP referrers</strong></li>
                <li>Add your domain (e.g. <code className="bg-muted px-1 rounded">https://yourapp.base44.app/*</code>)</li>
                <li>Under <strong>API restrictions</strong>, restrict to <strong>Cloud Firestore API</strong> only</li>
              </ol>
            </div>

            <hr className="border-border" />

            <div>
              <h3 className="font-semibold text-foreground mb-2">4. Service Account Permissions (Admin SDK)</h3>
              <ul className="space-y-2 text-xs ml-2">
                <li>• If using a <strong>service account</strong> (server-side), go to <strong>Project Settings → Service accounts</strong></li>
                <li>• Grant only the minimum IAM roles needed (e.g. <code className="bg-muted px-1 rounded">Cloud Datastore User</code> for read/write)</li>
                <li>• Avoid using <code className="bg-muted px-1 rounded">Owner</code> or <code className="bg-muted px-1 rounded">Editor</code> roles on service accounts</li>
                <li>• Rotate service account keys regularly and never commit them to source control</li>
              </ul>
            </div>

            <div className="bg-accent/30 p-3 rounded text-xs">
              <p className="font-medium text-foreground mb-1">Best Practice Summary:</p>
              <ul className="space-y-0.5">
                <li>✓ Use Firestore Rules to enforce who can read/write</li>
                <li>✓ Restrict your API key to your domain in Google Cloud Console</li>
                <li>✓ Enable Firebase Authentication before going live</li>
                <li>✓ Never expose service account keys in frontend code</li>
              </ul>
            </div>

          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}